### ISSUE TITLE
ContextProvider doesn't exist

### ISSUE THREAD

**Issue by kellianoy** [adaltas/ece-webtech-2021-fall#15]
# Issue on context provider

## Lab 7

Referring to the class documentation, this code ```<ContextProvider> </ContextProvider>``` that we need to put in `index.js` doesn't seem to work. 

## Questions

1. Is it because we should initialize the context inside of `index.js` and use instead ```<myContext.Provider></myContext.Provider>``` ?
2. If we don't need it, how should we initialize the line ``` export const myContext = React.createContext() ``` to have the values that we set in the ``` export const Provider```?

Thank you for your time.

### Refered Code in the index.md

```ReactDOM.render(
  <React.StrictMode>
    <ContextProvider>
      <CookiesProvider>
        <ThemeProvider theme={theme}>
          <App />
        </ThemeProvider>
      </CookiesProvider>
    </ContextProvider>
  </React.StrictMode>,
  document.getElementById('root')
);

**Comment by wdavidw** [comment]
Please refer to the [context doc](https://reactjs.org/docs/context.html):

It seems like you disregarded the first part, described in [section `Example - Context initialization`](https://github.com/adaltas/ece-webtech-2021-fall/blob/master/courses/webtech/modules/07.context/index.md?plain=1#L82-L113) of the course. Notice, it exports 2 things: the context, to be used by the `userContext` hook, as well as the context.Provider to be used in `index.js`.

**Comment by kellianoy** [comment]
## Answer

I see, I didn't interpret it that way. I imported both the `Context` and the `ContextProvider` within `index.js` and tried to combine them whereas I only need to use `Context Provider`. 

Thanks for your answer.

# Conclusion

## Issue

`Context` always returned null instead of my values & functions. I couldn't link the `Provider` and the `Context` together.

## How to fix this issue

Simply import the `Provider` from `App.js` in `index.js` and put `<Provider><\Provider>` at the appropriate spot.
