### ISSUE TITLE
Lab7 : missing '=' at Example - Context initialization

### ISSUE THREAD

**Issue by EliottElek** [adaltas/ece-webtech-2021-fall#16]
It appears that : 
`export const ContextProvider  ({
  children
}) => `
in the Example - Context initialization (index.md) part is missing an equal character. Should be : 
`export const ContextProvider = ({
  children
}) =>`

**Comment by sergkudinov** [comment]
Thanks,
Fixed in #5f711ac157c7e6926348bca55d42285071abf6b1
