### ISSUE TITLE
Lab 7 : context.js

### ISSUE THREAD

**Issue by EliseMalard** [adaltas/ece-webtech-2021-fall#18]
Hello, we tried to implement the context initialization as shown in the index.md : 
we import React and use state with the following line
`import React, {useState} from 'react'`

then we export : 
`export const Context = React.createContext();`
`export const ContextProvider = ({ children }) =>`

 and we've got the error : 

import React, {useState} from 'react'
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by wdavidw** [comment]
Elise, have you fixed your error or shall I looked at it ?

**Comment by EliseMalard** [comment]
It's okay I've fixed it this morning thank you
