### ISSUE TITLE
Lab6 Dex CORS error

### ISSUE THREAD

**Issue by rosemerel** [adaltas/ece-webtech-2021-fall#20]
127.0.0.1/:1 Access to XMLHttpRequest at 'http://127.0.0.1:5556/dex/token' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

index.js:1 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:117)

console.<computed> @ index.js:1
fetch @ Login.js:128
async function (async)
fetch @ Login.js:109
(anonymous) @ Login.js:131
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
xhr.js:210 POST http://127.0.0.1:5556/dex/token net::ERR_FAILED

**Comment by EtienneDx** [comment]
In your dex config, you need to specify the CORS policy. You can do it with this normally:

```
web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']
```

**Comment by wdavidw** [comment]
I confirm, once you get the `http` and `allowedOrigins`, I made you code work (it fails on the next step with your context usage). For this, you need to remove the `{headers:{'Access-Control-Allow-Origin': '*'}}` which you inserted.

**Comment by rosemerel** [comment]
http and allowed Origins were already set. I've deleted my context usage and the {headers:{'Access-Control-Allow-Origin': '*'}} but I still have errors. 

xhr.js:210 POST http://127.0.0.1:5556/dex/token 400 (Bad Request)

index.js:1 Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.onloadend (xhr.js:66)

**Comment by wdavidw** [comment]
Make sure to use a private window as well even if I don't suspect it to cause the problem.

**Comment by wdavidw** [comment]
I'll be in SC215 this afternoon if you want to pass by before or after.

**Comment by rosemerel** [comment]
I have a class programmed this afternoon but I'll try to pass

**Comment by wdavidw** [comment]
And always refresh the initial page (https://127.0.0.1:3000) because the code_verifier can only be used once.

**Comment by rosemerel** [comment]
I made it work by deleting the "/?code=eaj4nsu3zuvseomxcohgqysen&state=" that appears after the url 127.0.0.1:3000"

**Comment by wdavidw** [comment]
Ok, it means that you were calling twice Dex with the post request and the second query was in error because the code can only be used once.
