### ISSUE TITLE
Lab 6 : Internal Server Error

### ISSUE THREAD

**Issue by ThibaultECE** [adaltas/ece-webtech-2021-fall#22]
Hi, when following the trail for the lab 6 i stumble on an issue. After the identification via github and granting my consent, i get this before the callback :
![image](https://user-images.githubusercontent.com/90321277/142003164-5b57ab4d-fd0f-4703-af83-874039291b5f.png)

When looking at the exact error from the cmd it state :
"Failed to authenticate: github: failed to get token: oauth2: server response missing access_token"

For my dex config `:
issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: examples/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: webtech-frontend
  redirectURIs:
  - 'http://127.0.0.1:3000'
  name: 'Webtech'
  public: true

connectors:
- type: github
  id: github
  name: Github
  config:
    clientID: 988f4e790697f94564ef
    clientSecret: 511f28ba483fda810d0793a3faaa459ae01448f5
    redirectURI: http://127.0.0.1:5556/dex/callback

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"`

I search for fix but didn't find anything that would fit my problem.

**Comment by wdavidw** [comment]
I never got this error. What is strange with it is the notion of the access_token. You don't send an access_token to github, instead you receive an access_token from a post request.

**Comment by wdavidw** [comment]
You can always login with the admin@example.com email without github.

**Comment by ThibaultECE** [comment]
Yeah without github and with the normal email login it's working just fine. I will be closing the issue as it doesn't stop the progression of the lab, just were wondering if it was something that someone would have already see as i didn't find much on the web about it. Thank for the help and i will post a fix if i find one !
