### ISSUE TITLE
Error with dex when make build

### ISSUE THREAD

**Issue by mathisCAMARD** [adaltas/ece-webtech-2021-fall#33]
```
make build
-mod=mod not supported (can be '', 'readonly', or 'vendor')
storage/ent/generate.go:3: running "go": exit status 1
make: *** [Makefile:34 : generate] Erreur 1
```

**Comment by AnneCharlotteVgn** [comment]
I had the same issue on Linux. 
I used the following commands : 

rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.4.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

then you verify go installation with : 

go version

(The commands come from this website: https://go.dev/doc/install)

**Comment by wdavidw** [comment]
@mathisCAMARD please confirm if @AnneCharlotteVgn instructions fix your issue and, in such case, close the issue.

**Comment by mathisCAMARD** [comment]
It worked well, Thanks
