### ISSUE TITLE
[Console Issue] - Warning about camel case elements

### ISSUE THREAD

**Issue by kellianoy** [adaltas/ece-webtech-2021-fall#34]
# Warning inside of my code

## What happens

When I open the console inside of my channel page, I get this message several times, ~3 times and I can't seem to find the origin of this problem.

## Message
`Warning: React does not recognize the `textColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by EtienneDx** [comment]
Usually, that means you have an element looking something like this:

```jsx
<div textColor="sth"></div>
```

Whereas textColor is a css property, which means you should have a syntax looking like this:

```jsx
<div css={{ textColor: "sth" }}></div>
```

Try giving the line of the error or the component causing this error so that we can debug the problem

**Comment by kellianoy** [comment]
If it was this easy, I would have figured it out by now. The problem is that there is no mention of textColor whatsoever in my code. 

We suspect it is a problem with certain components from mui that create havoc in the code.

It is sending me on index.js to fix the error, however, there isn't much in this file.

Thanks for trying nonetheless.

**Comment by wdavidw** [comment]
We sort of suspected that `textColor` is a MUI component property which ends up as an HTML attribute. There are some open issues in MUI relative to this error. Closing since there is not much we could do about it.
