### ISSUE TITLE
Delete request trouble 

### ISSUE THREAD

**Issue by mattAmiral** [adaltas/ece-webtech-2021-fall#41]
Hi, 

I am having an issue when trying to delete an object from the database (i.e. channel or message).
More precisely for the channel deletion I face a 404 error code, signifying that the page in the back-end doesn't exist.
Here is the request I make in the front-end : 

```javascript
await axios.delete(`http://localhost:3002/channels/${channel.id} 
```

And I have added in the back-end(back-end/lib/app.js) the function to handle a channel deletion : 

```javascript 
app.delete('/channels/:id', async (req, res) => {
  const channel = await db.channels.delete(req.params.id)
  res.status(201).json(channel)
})
```
So from what I understood, I thought that adding this function and its associated path with the delete request should allow me to send a delete request with the same path. But it's not the case.

Does anyone know what I am doing wrong ?

Thanks in advance

**Comment by EliottElek** [comment]
Why are you making requests on port 3002 ? Doesn't you back-end api run on 3001 ?

**Comment by mattAmiral** [comment]
No my back-end runs on port 3002 because I have my port 3000 already used by my system (ubuntu), hence front runs on 3001 and back on 3002. 
If you were wondering, all the get/post requests work perfectly.

**Comment by kellianoy** [comment]
I have two ideas.

it's either ```await axios.delete(`http://localhost:3002/channels/${channel.id}``` that should actually be  ```await axios.delete(`http://localhost:3002/channels/${channel.id}`)``` or the variant with the header if you secured the request.

My second idea is that maybe you aren't using `db.del` in your back-end and are instead using `db.delete`.

**Comment by EliottElek** [comment]
If You receive a 404 error, it indicates that the path is not recognized. Make sure you put the right path and that the path is recognized by the back-end. 
After creating this 
`app.delete('/channels/:id', async (req, res) => {
  const channel = await db.channels.delete(req.params.id)
  res.status(201).json(channel)
})`
did you restart your back-end ?

**Comment by mattAmiral** [comment]
Thanks for your replies.
@kellianoy I will try what you suggest with await axios.delete and see what results I have.
I do use db.del and not db.delete, so this should not be the source of my problem. 

@EliottElek Normally the path is correct since I use it for my post/get request and it is recognized. But I will check again (mistakes happen so often). 
And yes I restarted the back-end several times.

**Comment by mattAmiral** [comment]
I finally managed to deal with it, and the error I had was in my function to delete channel in db.js.
