### ISSUE TITLE
Update Channel

### ISSUE THREAD

**Issue by Sheixxx** [adaltas/ece-webtech-2021-fall#42]
Hello,

I have a problem with the back-end for update a channel.
When I use axios.put, I have the following error : "store is not defined".
I don't understand how store works.

Can you please help me?

I attach screenshots of my code

![image](https://user-images.githubusercontent.com/46935021/146524692-1ea19fb6-05ed-4441-819a-27c5bf48a8ec.png)
![image](https://user-images.githubusercontent.com/46935021/146524303-bc42017f-50c5-4b38-97a1-dac98b4e7903.png)

**Comment by bloomkail** [comment]
Hello Benjamin,
It is deprecated code and should only be used as a placeholder for actual db  functions.
If you want to use those, you need to erase their code and write it from scratch using leveldb functions.
Hope it helps.

**Comment by Sheixxx** [comment]
Ok thank you Arnaud
