### ISSUE TITLE
errors whnen executing lab4 code (in app.js)

### ISSUE THREAD

**Issue by yanis92300** [adaltas/ece-webtech-2021-fall#9]
Hello, I have few errors I didn't manage to resolve when executing the lab4 code . Here is a screenshot : 

![image](https://user-images.githubusercontent.com/57595838/137632580-ca11b330-54a1-431b-b11d-af2891205317.png)

**Comment by comelite** [comment]
You can add 
```
/** @jsxRuntime classic */
```
to your file.
I hope this will help you

**Comment by EtienneDx** [comment]
I think a few students had this problem when running it with a node version which is too old.

**Comment by bloomkail** [comment]
You might have run into the same issue as us. To fix this, empty your `front-end` directory, then **do not create your own web pack using npx create-react-app**. Instead, import the content of the `lab` repository into `front-end`, and then simply use `npm install`.

**Comment by yanis92300** [comment]
> 
> 
> You might have run into the same issue as us. To fix this, empty your `front-end` directory, then **do not create your own web pack using npx create-react-app**. Instead, import the content of the `lab` repository into `front-end`, and then simply use `npm install`.

thanks it works !
